In [2]:
# 기본라이브러리 호출

import pandas as pd
import numpy as np

In [4]:
# 분석 라이브러리 호출
from sklearn.datasets import load_iris # 데이터
from sklearn.model_selection import train_test_split # 데이터 분할
from sklearn.tree import DecisionTreeClassifier # 분류알고리즘(의사결정나무)
from sklearn.metrics import accuracy_score # 평가지표(정확도) - 7가지 지표가 존재한다

In [6]:
iris = load_iris()
X_ftrs = iris.data
y_label = iris.target

In [9]:
# df 생성
iris_df = pd.DataFrame(X_ftrs, columns = iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [13]:
# df의 label 생성
iris_df['label'] = y_label
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [119]:
array1 = np.arange(1,11) # n-1 
array2 = np.arange(21,31) # n-1
array3 = np.arange(31,41) # n-1

train_test_split(array1, array2, array3, test_size=0.2, random_state=11)
# train_test_split(array2,test_size=0.2, random_state=11)

[array([ 3,  7,  5,  6,  2,  4,  1, 10]),
 array([8, 9]),
 array([23, 27, 25, 26, 22, 24, 21, 30]),
 array([28, 29]),
 array([33, 37, 35, 36, 32, 34, 31, 40]),
 array([38, 39])]

In [122]:
## train과 test를 분할
# df도, ndarray도 동일하게 train_test_split 적용이 가능합니다.

X_train, X_test, y_train, y_test  = train_test_split(X_ftrs, y_label, test_size=0.2, random_state=11)

In [127]:
## 데이터 크기를 확인
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

X_train shape: (120, 4)
X_test shape: (30, 4)
y_train shape: (120,)
y_test shape: (30,)


In [129]:
# 학습 및 예측을 수행 :: fit, predict를 활용

dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train,y_train)

pred_dt = dt_clf.predict(X_test) # X_test를 넣어서 도출된 예측 y 

In [145]:
?dt_clf()

Object `dt_clf()` not found.


In [138]:
# 평가지표로 평가 :: (Accuracy)

from sklearn.metrics import accuracy_score

result_acc = accuracy_score(y_test, pred_dt)
print('의사결정나무 정확도:',np.round(result_acc,4))

의사결정나무 정확도: 0.9333


In [139]:
# end of file 