### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing) 

#### 1.특정한 데이터만 추출
#### 2.슬라이싱(Slicing)
#### 3.팬시 인덱싱(Fancy Indexing)
#### 4.불리언 인덱싱(Boolean Indexing)

In [1]:
import numpy as np
import pandas as pd

In [2]:
array1d = np.arange(1,10) 
print(array1d)
array1d[array1d>5]

[1 2 3 4 5 6 7 8 9]


array([6, 7, 8, 9])

In [3]:
### 불리언 결과값으로 인덱싱

array1d>5
indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
result = array1d[indexes]
print('불리언 인덱스로 필터링한 결과:', result)

불리언 인덱스로 필터링한 결과: [6 7 8 9]


In [4]:
### for문을 통한 인덱싱
for i in array1d:
    if i >5:
        print(i, end = ' ')
    else:
        pass

6 7 8 9 

In [5]:
### 일반 인덱싱으로 호출
array1d
indexes2 = np.array([5,6,7,8])
array1d[indexes2]

array([6, 7, 8, 9])

### 행렬의 정렬 - sort()와 argsort()

In [6]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array) # 결과값이 출력 -> 원본이 안바뀜
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 반환된 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort() # 결과값이 출력이 안되면 -> 원본이 바뀜
print('ndarray.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('ndarray.sort() 호출 후 반환된 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 반환된 원본 행렬: [3 1 9 5]
ndarray.sort() 호출 후 반환된 정렬 행렬: None
ndarray.sort() 호출 후 반환된 원본 행렬: [1 3 5 9]


In [7]:
### 내림차순 정렬
sort_desc_array = np.sort(org_array)[::-1]
print(sort_desc_array)

[9 5 3 1]


### 데이터 핸들링 - 판다스

www.kaggle.com/c/titanic/data 

In [8]:
import pandas as pd
titan_df = pd.read_csv('./data/train.csv')
titan_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [9]:
print('df의 크기:', titan_df.shape)

df의 크기: (891, 12)


In [10]:
titan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [11]:
titan_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
### 컬럼명 변경

## 바꾸는 방법 1 :: 바뀐 상태를 reassign (재할당)
titan_df1 = titan_df.rename(columns= {'Sex':'Gender'})
titan_df1.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [13]:
## 바꾸는 방법 2 :: inplace = True or False
## 원본 데이터 수정

titan_df.rename(columns= {'Sex':'Gender'}, inplace = True)

In [14]:
titan_df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [15]:
### 성별의 구성, 등급의 구성 등의 value값 살펴보기
### 1차원의 데이터 형태 :: Series
### 2차원의 data frame = Series + Series 

print(titan_df['Gender'].value_counts())

print(titan_df.Pclass.value_counts())

male      577
female    314
Name: Gender, dtype: int64
3    491
1    216
2    184
Name: Pclass, dtype: int64


In [16]:
### reset_index() 우리가 생성했었던 데이터의 index를
### 재정렬한다.

titan_df_test = titan_df['Pclass'].value_counts().reset_index()

print(type(titan_df_test)) ### 2차원의 df
print(type(titan_df['Pclass'])) ### 1차원의 series

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [17]:
### 파생변수 생성 = 새로운 컬럼을 생성한다

titan_df['Age_by_10'] = titan_df['Age'] * 10
titan_df['Fam_no'] = titan_df['SibSp'] + titan_df.Parch + 1
titan_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_by_10  Fam_no  
0        0         A/5 21171   7.2500   NaN        S      220.0       2  
1        0          PC 17599  71.2833   C85        C      380.0       2  
2        0  STON/O2. 3101282   7.9250   NaN        S      260.0       1  
3        0            113803  53.1000  C123        S      350.0       2  
4        0            373450   8.0500   NaN        S      350.0       1  
..     ...               ...      ...   ...      ...        ...     ...  
886      0            211536  13.0000   NaN        S      270.0       1  
887      0            112053  30.0000   B42        S      190.0       1  
888      2        W./C. 6607  23.4500   NaN        S        NaN       4  
889      0            111369  30.0000  C148        C      260.0       1  
890      0            370376   7.7500   NaN        Q      320.0       1  

[891 rows x 14 columns]

In [18]:
### 해당 컬럼 삭제 
## 변수에 상태를 저장한다 -1 

titan_df1 = titan_df.drop(['Age_by_10','Fam_no'], axis = 1)
titan_df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [19]:
### 해당컬럼 삭제 - 2
## 원본 데이터 지우기
titan_df.drop(['Age_by_10','Fam_no'], axis =1, inplace=True)

In [20]:
titan_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [21]:
### 해당 행 삭제

pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('### before axis 0 drop ###')
print(titan_df.head(3))

titan_df.drop([0,1,2], axis=0, inplace=True)

print('### after axis 0 drop ###')
print(titan_df.head(3))

### before axis 0 drop ###
   PassengerId  Survived  Pclass            Name  Gender   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
### after axis 0 drop ###
   PassengerId  Survived  Pclass            Name  Gender   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


In [22]:
# end of file 