In [1]:
import pandas as pd

In [3]:
t_df=pd.read_csv('./train.csv')

In [18]:
t_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
t_df['Age'].isna().value_counts()

False    714
True     177
Name: Age, dtype: int64

In [12]:
t_df['Age'].isna().count()

891

In [17]:
t_df['Age'].isna().sum()

177

In [4]:
t_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
%autosau

#### 팬시 인덱싱(Fancy indexing) 

In [1]:
import numpy as np

In [2]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())


array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())
array2d

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array1d=np.arange(start=1, stop=10)
#[] 안에 array 1d> 5 Boolean indexing을 적용
array3= array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값:',array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [6]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [9]:
for i in array1d:
    if i > 5:
        print(i)
    else:
        pass

6
7
8
9


In [12]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3= array1d[boolean_indexes]
print('일반 인덱스로 필터링 결과:', array3)

일반 인덱스로 필터링 결과: [6 7 8 9]


### 행렬의 정렬 - sort( )와 argsort( )

In [14]:
org_array = np.array([3,1,9,5])
print('원본행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

#npdarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)


원본행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


##### 내림차순 정렬

In [15]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


#### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [3]:
A= np.array([[1,2,3],
            [4,5,6]])

B= np.array([[7,8],
            [9,10],
            [11,12]])

np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

#### 전치 행렬

In [6]:
A= np.array([[1,2],
             [3,4]])

transpose_mat=np.transpose(A)
print("A의 전치행렬:\n", transpose_mat)

B= np.array([[1,2],
             [3,4],
             [5,6]])
transpose_mat1=np.transpose(B)
print("B의 전치행렬:\n", transpose_mat1)

A의 전치행렬:
 [[1 3]
 [2 4]]
B의 전치행렬:
 [[1 3 5]
 [2 4 6]]


## 데이터 핸들링 - 판다스 
www.kaggle.com/c/titanic/data

In [4]:
import pandas as pd

In [5]:
titanic_df=pd.read_excel('./train.xlsx')
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
print('DataFrame 크기:', titanic_df.shape)

DataFrame 크기: (891, 12)


In [7]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [8]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [9]:
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [10]:
value_counts= titanic_df["Pclass"].value_counts()
print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [11]:
titanic_pclass=titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [12]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [13]:
value_counts=titanic_df.value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
PassengerId  Survived  Pclass  Name                                                  Sex     Age   SibSp  Parch  Ticket    Fare      Cabin  Embarked
890          1         1       Behr, Mr. Karl Howell                                 male    26.0  0      0      111369    30.0000   C148   C           1
337          0         1       Pears, Mr. Thomas Clinton                             male    29.0  1      0      113776    66.6000   C2     S           1
332          0         1       Partner, Mr. Austen                                   male    45.5  0      0      113043    28.5000   C124   S           1
330          1         1       Hippach, Miss. Jean Gertrude                          female  16.0  0      1      111361    57.9792   B18    C           1
328          1         2       Ball, Mrs. (Ada E Hall)                               female  36.0  0      0      28551     13.0000   D      S           1
                                             

### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호변환

In [24]:
import numpy as np

col_name1=['col1']
list1=[1,2,3]
array1= np.array(list1)
print('array1 shape:', array1.shape)
#리스트를 이용하여 DataFrame 생성.
df_list1=pd.DataFrame(list1,columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n',df_list1)
#넘파이 ndarray를 통해 DataFrame 생성
df_array1=pd.DataFrame(array1,columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n',df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [26]:
#3개의 칼럼명이 필요함.
col_name2=['col1','col2','col3']

#2행 x 3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1,2,3],
         [11,12,13]]

array2 = np.array(list2)
print('array2 shape:\n',array2.shape)
df_list2=pd.DataFrame(list2,columns=col_name2)
print('2차원 리스트로 만든 DataFrame\n:',df_list2)
df_array2=pd.DataFrame(array2,columns=col_name2)
print('2차원  ndarray로 만든 DataFrame\n:',df_array2)

array2 shape:
 (2, 3)
2차원 리스트로 만든 DataFrame
:    col1  col2  col3
0     1     2     3
1    11    12    13
2차원  ndarray로 만든 DataFrame
:    col1  col2  col3
0     1     2     3
1    11    12    13


In [27]:
#key는 문자열 컬럼명으로 매핑, Value는 리스트 형(또는 ndarray) 컬럼 데이터로 매핑
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n',df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [32]:
#DataFrame을 ndarray로 변환
array3=df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [35]:
#DataFrame을 리스트로 변환
list3=df_dict.values.tolist()
print('\n df_dict.tolist()타입:',type(list3))
print(list3)
#DataFrame을 딕셔너리로 변환
dict3=df_dict.to_dict('list')
print('\n df_dict.to_dict()타입:',type(dict3))
print(dict3)


 df_dict.tolist()타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict()타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [32]:
titanic_df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [33]:
titanic_df['Age_0']=0
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [34]:
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

In [42]:
titanic_df['Age_by_10']=titanic_df['Age_by_10']+100
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      920.0   
1      0          PC 17599  71.2833   C85        C      0     1080.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      960.0   

   Family_No  
0          2  
1          2  
2          1

In [56]:
titanic_drop_df=titanic_df.drop("Age_0",axis=1,inplace=True)
titanic_drop_df

KeyError: "['Age_0'] not found in axis"

In [57]:
#원본에는 살아있는 Age_o
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      920.0          2  
1      0          PC 17599  71.2833   C85        C     1080.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      960.0          1

In [58]:
drop_result=titanic_df.drop(['Age_by_10','Family_No'],axis=1,inplace=True)
print('inplace=True로 drop후 반환된 값:',drop_result)
titanic_df.head(3)

inplace=True로 drop후 반환된 값: None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [59]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('### before axis 0 drop ###')
print(titanic_df.head(3))

titanic_df.drop([0,1,2],axis=0, inplace=True)

print('### after axis 0 drop ###')
print(titanic_df.head(3))

### before axis 0 drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
### after axis 0 drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


In [60]:
titanic_df

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket      Fare        Cabin Embarked
3              4         1       1  Futrelle, M...  female  35.0      1      0          113803   53.1000         C123        S
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450    8.0500          NaN        S
5              6         0       3  Moran, Mr. ...    male   NaN      0      0          330877    8.4583          NaN        Q
6              7         0       1  McCarthy, M...    male  54.0      0      0           17463   51.8625          E46        S
7              8         0       3  Palsson, Ma...    male   2.0      3      1          349909   21.0750          NaN        S
8              9         1       3  Johnson, Mr...  female  27.0      0      2          347742   11.1333          NaN        S
9             10         1       2  Nasser, Mrs...  female  14.0      1      0          237736   30.0708          NaN        C
10            11         1       3  Sandstrom, ...  female   4.0      1      1         PP 9549   16.7000           G6        S
11            12         1       1  Bonnell, Mi...  female  58.0      0      0          113783   26.5500         C103        S
12            13         0       3  Saundercock...    male  20.0      0      0       A/5. 2151    8.0500          NaN        S
13            14         0       3  Andersson, ...    male  39.0      1      5          347082   31.2750          NaN        S
14            15         0       3  Vestrom, Mi...  female  14.0      0      0          350406    7.8542          NaN        S
15            16         1       2  Hewlett, Mr...  female  55.0      0      0          248706   16.0000          NaN        S
16            17         0       3  Rice, Maste...    male   2.0      4      1          382652   29.1250          NaN        Q
17            18         1       2  Williams, M...    male   NaN      0      0          244373   13.0000          NaN        S
18            19         0       3  Vander Plan...  female  31.0      1      0          345763   18.0000          NaN        S
19            20         1       3  Masselmani,...  female   NaN      0      0            2649    7.2250          NaN        C
20            21         0       2  Fynney, Mr....    male  35.0      0      0          239865   26.0000          NaN        S
21            22         1       2  Beesley, Mr...    male  34.0      0      0          248698   13.0000          D56        S
22            23         1       3  McGowan, Mi...  female  15.0      0      0          330923    8.0292          NaN        Q
23            24         1       1  Sloper, Mr....    male  28.0      0      0          113788   35.5000           A6        S
24            25         0       3  Palsson, Mi...  female   8.0      3      1          349909   21.0750          NaN        S
25            26         1       3  Asplund, Mr...  female  38.0      1      5          347077   31.3875          NaN        S
26            27         0       3  Emir, Mr. F...    male   NaN      0      0            2631    7.2250          NaN        C
27            28         0       1  Fortune, Mr...    male  19.0      3      2           19950  263.0000  C23 C25 C27        S
28            29         1       3  O'Dwyer, Mi...  female   NaN      0      0          330959    7.8792          NaN        Q
29            30         0       3  Todoroff, M...    male   NaN      0      0          349216    7.8958          NaN        S
30            31         0       1  Uruchurtu, ...    male  40.0      0      0        PC 17601   27.7208          NaN        C
31            32         1       1  Spencer, Mr...  female   NaN      1      0        PC 17569  146.5208          B78        C
32            33         1       3  Glynn, Miss...  female   NaN      0      0          335677    7.7500          NaN        Q
..           ...       ...     ...             ...     ...   ...    