## 행렬의 정렬 - sort()와 argsort()

In [2]:
import pandas as pd
import numpy as np

In [5]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

원본 행렬: [3 1 9 5]


In [9]:
## np.sort()로 정렬
sort_array1= np.sort(org_array) 
print('sort_array1:', sort_array1)
print('org_array:', org_array)

## ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('sort_array2:', sort_array2)
print('org_array:', org_array)

sort_array1: [1 3 5 9]
org_array: [1 3 5 9]
sort_array2: None
org_array: [1 3 5 9]


In [12]:
### 내림차순으로 정렬
sorted_desc = np.sort(org_array)[::-1]
print(sorted_desc)

[9 5 3 1]


#### Axis 축을 기준으로 하여 정렬

In [15]:
array2d = np.array([[8,1],
                    [7,12]])

In [16]:
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]


In [17]:
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

컬럼 방향으로 정렬:
 [[ 1  8]
 [ 7 12]]


##### argsort()함수 :: 정렬된 행렬의 인덱스 반환! 

In [20]:
### 오름차순

org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 index:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 index: [1 0 3 2]


In [22]:
### 내림차순 - [9,5,3,1]
#              2 3 0 1  

org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)[::-1]
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 index:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 index: [2 3 0 1]


In [23]:
A= np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n', transpose_mat)

B= np.array([[1,2],
            [3,4],
            [5,6]])

transpose_mat1=np.transpose(B)
print('B의 전치행렬:\n', transpose_mat1)

A의 전치행렬:
 [[1 3]
 [2 4]]
B의 전치행렬:
 [[1 3 5]
 [2 4 6]]


In [24]:
# end of file